//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Couriers
    {
        public int CourierId { get; set; }
        public string CourierPersonalCode { get; set; }
        public string CourierTz { get; set; }
        public string CourierFirstName { get; set; }
        public string CourierLastName { get; set; }
        public string CourierAddress { get; set; }
        public string CourierCity { get; set; }
        public string CourierPhone { get; set; }
        public Nullable<int> CourierStatus { get; set; }
        public Nullable<int> CourierTypeOfTransport { get; set; }
        public Nullable<double> Lon { get; set; }
        public Nullable<double> Lat { get; set; }
    }
}
