//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CourierCompanyEntities : DbContext
    {
        public CourierCompanyEntities()
            : base("name=CourierCompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coment> Coment { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<CourierPackage> CourierPackage { get; set; }
        public virtual DbSet<Couriers> Couriers { get; set; }
        public virtual DbSet<CouriersComments> CouriersComments { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<MadeShipments> MadeShipments { get; set; }
        public virtual DbSet<PackageAddress> PackageAddress { get; set; }
        public virtual DbSet<Packages> Packages { get; set; }
    }
}
