//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Packages()
        {
            this.PackagesToCouriers = new HashSet<PackagesToCouriers>();
        }
    
        public int PackageId { get; set; }
        public string CollectionAddress { get; set; }
        public Nullable<int> Cfloor { get; set; }
        public string Destination { get; set; }
        public Nullable<int> Dfloor { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string SenderPhone { get; set; }
        public string InvoiceName { get; set; }
        public string PhoneReceivesShippingPac { get; set; }
        public string CompanyName { get; set; }
        public string FullName { get; set; }
        public string DuringSending { get; set; }
        public Nullable<int> Weigth { get; set; }
        public Nullable<System.DateTime> DateNow { get; set; }
        public string Description { get; set; }
        public string CommendsPac { get; set; }
        public string Status { get; set; }
        public Nullable<double> SourcePackageLon { get; set; }
        public Nullable<double> SourcePackageLat { get; set; }
        public Nullable<double> DestinetionPackageLon { get; set; }
        public Nullable<double> DestinationPackageLat { get; set; }
        public Nullable<int> CourierCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackagesToCouriers> PackagesToCouriers { get; set; }
    }
}
